# @package _global_
# ==============================================================================
# OrangeCashMachine — Exchange: Bybit
# ==============================================================================

exchanges:
  bybit:
    enabled: true
    enableRateLimit: true
    auto_discover_symbols: false

    credentials:
      apiKey: ${oc.env:BYBIT_API_KEY,""}
      secret: ${oc.env:BYBIT_API_SECRET,""}

    options:
      adjustForTimeDifference: true

    markets:
      spot:
        enabled: true
        symbols: [BTC/USDT]
      futures:
        enabled: true
        defaultType: swap
        symbols:
          - BTC/USDT:USDT
          - BTC/USD:BTC
