# @package _global_
# ==============================================================================
# OrangeCashMachine — Exchange: KuCoin Futures
# ==============================================================================

exchanges:
  kucoinfutures:
    enabled: true
    enableRateLimit: true
    test_symbol: "BTC/USDT:USDT"
    auto_discover_symbols: false

    credentials:
      apiKey: ${oc.env:KUCOIN_API_KEY,""}
      secret: ${oc.env:KUCOIN_API_SECRET,""}
      password: ${oc.env:KUCOIN_PASSPHRASE,""}

    options:
      adjustForTimeDifference: true
      defaultType: swap

    markets:
      spot:
        enabled: false
        symbols: []
      futures:
        enabled: true
        defaultType: swap
        symbols:
          - BTC/USDT:USDT
